baseURL: "https://rahab-nadir.github.io/"
title: Rahab Nadir
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Resume
          url: cv_rosa_032026.pdf
          weight: 3 
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am an Erasmus Mundus Scholar in Public Sector Innovation & e-Governance"
    author: Rahab Nadir
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rahab Nadir
          subtitle: "I am Rahab Nadir. I am Rahab Nadir, an MSc candidate in Public Sector Innovation and e-Governance through the PIONEER Erasmus Mundus Joint Master’s Programme, with academic training across KU Leuven, the University of Münster, and TalTech. My work focuses on the intersection of digital technologies, public institutions, and policy. <br><br> I am interested in how digital infrastructures are designed, governed, and implemented across public-sector systems. "
          imageUrl: "picture2.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Rahab Nadir
          buttons:
            - name: LinkedIn
              url: https://www.linkedin.com/in/rahabnadir/
            - name: Talks
              url: talks/
            - name: Resume
              url: cv_rvde_2026.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:rahabnadir95@gmail.com
        - name: Location
          url: location/


        - name: LinkedIn
          url: https://www.linkedin.com/in/rahabnadir/
        - name: ORCID
          url: https://orcid.org/0009-0006-6332-8515
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rahab Nadir"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
